services:
  load-balancer:
    image: lb-image
    ports:
      - "80:80"
    volumes:
      - "./load-balancer/nginx.conf:/etc/nginx/nginx.conf"
      - "./load-balancer/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      app_net:
        ipv4_address: 172.20.0.10

  executor1:
    image: executor-image
    networks:
      app_net:
        ipv4_address: 172.20.0.2
    env_file:
      - .env
    volumes:
      - /home/data:/home/data
    
  executor2:
    image: executor-image
    networks:
      app_net:
        ipv4_address: 172.20.0.3
    env_file:
      - .env
    volumes:
      - /home/data:/home/data

  executor3:
    image: executor-image
    networks:
      app_net:
        ipv4_address: 172.20.0.4
    env_file:
      - .env
    volumes:
      - /home/data:/home/data

  controller1:
      image: controller-image
      networks:
        app_net:
          ipv4_address: 172.20.0.12
      env_file:
        - .env
      environment:
        - MAIN_EXECUTOR_IDX=0
      volumes:
        - /home/data:/home/data

  controller2:
      image: controller-image
      networks:
        app_net:
          ipv4_address: 172.20.0.13
      env_file:
        - .env
      environment:
        - MAIN_EXECUTOR_IDX=1
      volumes:
        - /home/data:/home/data

  controller3:
      image: controller-image
      networks:
        app_net:
          ipv4_address: 172.20.0.14
      env_file:
        - .env
      environment:
        - MAIN_EXECUTOR_IDX=2
      volumes:
        - /home/data:/home/data 

  react-frontend:
    image: front-image
    ports:
      - "4000:80" 
    networks:
      app_net:
        ipv4_address: 172.20.0.15
    env_file:
        - .env                   

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
