services:
  load-balancer:
    image: lb-image
    ports:
      - "80:80"
    volumes:
      - "./load-balancer/nginx.conf:/etc/nginx/nginx.conf"
      - "./load-balancer/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      app_net:
        ipv4_address: 172.20.0.10

  node1:
    image: node-image
    networks:
      app_net:
        ipv4_address: 172.20.0.2
    env_file:
      - .env
    volumes:
      - /home/data:/home/data
    
  node2:
    image: node-image
    networks:
      app_net:
        ipv4_address: 172.20.0.3
    env_file:
      - .env
    volumes:
      - /home/data:/home/data

  node3:
    image: node-image
    networks:
      app_net:
        ipv4_address: 172.20.0.4
    env_file:
      - .env
    volumes:
      - /home/data:/home/data

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"