version: '3.8'

services:
  load-balancer:
    image: kicper231/lb-image:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      app_net:
        ipv4_address: 172.20.0.10

  executor1:
    image: kicper231/executor-image:latest
    networks:
      app_net:
        ipv4_address: 172.20.0.2
    env_file:
      - .env
    volumes:
      - "./data:/home/data"
    
  executor2:
    image: kicper231/executor-image:latest
    networks:
      app_net:
        ipv4_address: 172.20.0.3
    env_file:
      - .env
    volumes:
      - "./data:/home/data"

  executor3:
    image: kicper231/executor-image:latest
    networks:
      app_net:
        ipv4_address: 172.20.0.4
    env_file:
      - .env
    volumes:
      - "./data:/home/data"

  controller1:
    image: kicper231/controller-image:latest
    networks:
      app_net:
        ipv4_address: 172.20.0.12
    env_file:
      - .env
    environment:
      - MAIN_EXECUTOR_IDX=0
    volumes:
      - "./data:/home/data"

  controller2:
    image: kicper231/controller-image:latest
    networks:
      app_net:
        ipv4_address: 172.20.0.13
    env_file:
      - .env
    environment:
      - MAIN_EXECUTOR_IDX=1
    volumes:
      - "./data:/home/data"

  controller3:
    image: kicper231/controller-image:latest
    networks:
      app_net:
        ipv4_address: 172.20.0.14
    env_file:
      - .env
    environment:
      - MAIN_EXECUTOR_IDX=2
    volumes:
      - "./data:/home/data"

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/24"
