services:
  load-balancer:
    image: haproxy:latest
    container_name: haproxy-load-balancer
    ports:
      - "80:80"
    volumes:
      - "../ha-proxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    networks:
      app_net:
        ipv4_address: 172.20.0.10

  executor1:
    image: executor-image
    networks:
      app_net:
        ipv4_address: 172.20.0.2
    env_file:
      - ./.env 
    volumes:
      - ./data:/home/data/
    
  executor2:
    image: executor-image
    networks:
      app_net:
        ipv4_address: 172.20.0.3
    env_file:
      - ./.env
    volumes:
      - ./data:/home/data/

  executor3:
    image: executor-image
    networks:
      app_net:
        ipv4_address: 172.20.0.4
    env_file:
      - ./.env
    volumes:
      - ./data:/home/data/

  controller1:
    image: controller-image
    networks:
      app_net:
        ipv4_address: 172.20.0.12
    env_file:
      - ./.env
    environment:
        - MAIN_EXECUTOR_IDX=0
    volumes:
      - ./data:/home/data/

  controller2:
    image: controller-image
    networks:
      app_net:
        ipv4_address: 172.20.0.13
    env_file:
      - ./.env
    environment:
      - MAIN_EXECUTOR_IDX=1
    volumes:
      - ./data:/home/data/

  controller3:
    image: controller-image
    networks:
      app_net:
        ipv4_address: 172.20.0.14
    env_file:
      - ./.env
    environment:
        - MAIN_EXECUTOR_IDX=2
    volumes:
      - ./data:/home/data/

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
